# File paths are assuming that the wd is where this source file is.
# These paths are within the "Box" folder (this file's location), and may need to be updated
# to the user's file structure

rm(list = ls())
library(here)
library(tidyverse)
library(patchwork)
library(HDInterval)
library(RColorBrewer)

# plot theme
theme_cw <- function () { 
     theme_bw(base_size=12) %+replace% 
          theme(
               panel.background = element_blank(), 
               plot.background = element_blank(), 
               axis.ticks = element_line(colour = "grey70", size = rel(0.5)),
               panel.grid.minor = element_blank(), 
               panel.grid.major = element_blank(),
               legend.background = element_blank(), 
               legend.key = element_blank(),
               strip.background = element_blank(), 
               complete = TRUE
          )
}

### Box Figure part 1: different formulas for lambda ---------------

# monotonic lambda data
# Model fits generated by monoLambda_envAlpha_modelFit.R file
# These paths are within the "Box" folder (this file's location), and may need to be updated
# to the user's file structure

# true value
load('BH_simulations/test_multiple_simulations.RData')
sim <- simulations[[8]]
FullSim <- sim$simulation
TrueVals <- sim$parameters

load(here("BH_simulations/Box/StanFits/monoLambda_envAlpha/N200_FinalFit.rdata"))
PostLength <- length(Posteriors$alpha_generic[,1])
Focal <- 8

# individual draws from the posterior
n = 50
env.seq <- seq(-2, 2, length.out = n)
lambda.ei <- tibble(env.seq = rep(env.seq, times = PostLength), 
                    post = rep(1:PostLength, each = n), 
                    lambda.int = rep(Posteriors$lambdas[,1], each = n),
                    lambda.slope = rep(Posteriors$lambdas[,2], each = n))
lambda.ei$lambda.mono <- lambda.ei %>% with(exp(lambda.int + lambda.slope*env.seq))
lambda.ei$post <- as.factor(lambda.ei$post)

# sample 1000 from this to make graphing faster
sample.use <- sample(1:PostLength, size = 1000)
lambda.ei.small <- filter(lambda.ei, post %in% sample.use)
lambda.ei.small$ind <- 'ind'

# average from the posterior (could leave this out)
post.mean <- mean(Posteriors$lambdas[,1])
post.env <- mean(Posteriors$lambdas[,2])
lambda.post <- tibble(env.seq, post = as.factor(0), ind = 'post.mean', 
                      lambda.int = rep(post.mean, each = n),
                      lambda.slope = rep(post.env, each = n))
lambda.post$lambda.mono <- lambda.post %>% with(exp(lambda.int + lambda.slope*env.seq))

# true value calculations
lambda.mean <- with(TrueVals, lambda.mean[species == Focal])
lambda.env <- with(TrueVals, lambda.env[species == Focal])
lambda.true <- tibble(env.seq, post = as.factor(0), ind = 'true', 
                      lambda.int = rep(lambda.mean, each = n),
                      lambda.slope = rep(lambda.env, each = n))
lambda.true$lambda.mono <- lambda.true %>% with(exp(lambda.int + lambda.slope*env.seq))

lambda.comp <- rbind(lambda.post, lambda.true)

# calculate comparisons
(lambda.mean - post.mean)/lambda.mean
(lambda.env - post.env)/lambda.env

p.mono <- ggplot(lambda.ei.small, aes(x = env.seq, y = lambda.mono)) + 
        geom_line(aes(group = post), alpha = 0.02, color = 'grey50') + 
        geom_line(data = lambda.comp, aes(color = ind, linetype = ind)) +
        scale_color_manual(values = c('black','red'), name = '', 
                           labels = c('Modeled','True')) + 
        scale_linetype_manual(values = c('dashed','solid'), name = '', 
                              labels = c('Modeled','True')) + 
        theme_cw() + 
        theme(legend.position = c(0.2, 0.9)) +
        ylab(expression(lambda[ei])) +
        xlab('Environment') +
        theme(axis.title.y = element_text(size = 16))

## Same process with optimum lambda
# Model fits generated by optLambda_constAlpha_modelFit.R file
# These paths are within the "Box" folder (this file's location), and may need to be updated
# to the user's file structure
load(here("BH_simulations/Box/StanFits/optLambda_envAlpha/N200_FinalFit.rdata"))
PostLength <- length(Posteriors$lambda_max)
Focal <- 10

# individual draws from the posterior
n = 50
env.seq <- seq(-2, 2, length.out = n)
lambda.ei <- tibble(env.seq = rep(env.seq, times = PostLength), 
                    post = rep(1:PostLength, each = n), 
                    lambda.max = rep(Posteriors$lambda_max, each = n),
                    z.env = rep(Posteriors$lambda_opt, each = n),
                    sigma.env = rep(Posteriors$lambda_width, each = n))
lambda.ei$lambda.opt <- lambda.ei %>% 
     with(lambda.max * exp(-((z.env - env.seq)/(2*sigma.env))^2))
lambda.ei$post <- as.factor(lambda.ei$post)

# sample 1000 from this to make graphing faster
sample.use <- sample(1:PostLength, size = 1000)
lambda.ei.small <- filter(lambda.ei, post %in% sample.use)
lambda.ei.small$ind <- 'ind'

# average from the posterior (could leave this out)
post.max <- mean(Posteriors$lambda_max)
post.z.env <- mean(Posteriors$lambda_opt)
post.sigma.env <- mean(Posteriors$lambda_width)
lambda.post <- tibble(env.seq, post = as.factor(0), ind = 'post.mean', 
                      lambda.max = rep(post.max, each = n),
                      z.env = rep(post.z.env, each = n),
                      sigma.env = rep(post.sigma.env, each = n))
lambda.post$lambda.opt <- lambda.post %>% 
     with(lambda.max * exp(-((z.env - env.seq)/(2*sigma.env))^2))


# true value
TrueVals <- read.csv(here("BH_simulations/Box/SimulationsDataFiles/parameters_opt.csv"))
lambda.max <- with(TrueVals, lambda.max[species == Focal])
z.env <- with(TrueVals, z.env[species == Focal])
sigma.env <- with(TrueVals, sigma.env[species == Focal])
lambda.true <- tibble(env.seq, post = as.factor(0), ind = 'true', 
                      lambda.max = rep(lambda.max , each = n),
                      z.env = rep(z.env , each = n),
                      sigma.env = rep(sigma.env, each = n))
lambda.true$lambda.opt <- lambda.true %>% 
     with(lambda.max * exp(-((z.env - env.seq)/(2*sigma.env))^2))

# comparisons
(z.env - post.z.env)/z.env
(sigma.env - post.sigma.env)/sigma.env
(lambda.max - post.max)/lambda.max


p.opt <- ggplot(lambda.ei.small, aes(x = env.seq, y = lambda.opt)) + 
     geom_line(aes(group = post), alpha = 0.02, color = 'grey50') + 
     geom_line(data = lambda.true, color = 'red') +
     geom_line(data = lambda.post, color = 'black', linetype = 'dashed') + 
     theme_cw() + 
     ylab(expression(lambda[ei])) +
     xlab('Environment') +
     theme(axis.title.y = element_text(size = 16))

### Box figure part 2: without species x env relationships------------

# x axis of environmental condition
n = 50
env.seq <- seq(-2, 2, length.out = n)

# load in the model fit
# Phosphorous
load(here("BH_simulations/Box/StanFits/monoLambda_constAlpha/N200_FinalFit.rdata"))
Post <- rstan::extract(FinalFit)

# Create objects to hold the mean and credible interval values for the intraspecific
#  and generic alpha values
GenericPlot <- array(NA, dim = c(3, n))
IntraPlot <- array(NA, dim = c(3, n))

# Create an object to hold the alpha values for any species identified by the sparse
#  modeling approach as deviating from the generic value
SpecificPlot <- array(NA, dim = c(2, 3, n))

# Now calculate the alpha_e,i,j values for intraspecific alphas (IntraPlot), any heterospecifics that
#  affect the focal species as an average heterospecific neighbor (GenericPlot), and for any species
#  that differ from that generic heterospecific effect (SpecificPlot)
for(i in 1:n){
        # Calculate the posterior distribution for the relevant alpha_i,j
        GenericPost <- exp(Post$alpha_generic)
        Sp1Post <- exp(Post$alpha_generic + Post$alpha_hat_ij[,6])
        Sp2Post <- exp(Post$alpha_generic + Post$alpha_hat_ij[,14])
        IntraPost <- exp(Post$alpha_intra)
        # Now store the mean and 95% CI for these posteriors
        GenericPlot[1,i] <- mean(GenericPost)
        GenericPlot[2:3,i] <- HDInterval::hdi(GenericPost)
        IntraPlot[1,i] <- mean(IntraPost)
        IntraPlot[2:3,i] <- HDInterval::hdi(IntraPost)
        SpecificPlot[1,1,i] <- mean(Sp1Post)
        SpecificPlot[1,2:3,i] <- HDInterval::hdi(Sp1Post)
        SpecificPlot[2,1,i] <- mean(Sp2Post)
        SpecificPlot[2,2:3,i] <- HDInterval::hdi(Sp2Post)
}


AlphaRange <- c(0, 0.08)
AlphaLab <- expression(alpha["e,i,j"])

DarkCols <- brewer.pal(n = 8, name = "Dark2")
LambdaCols <- DarkCols[3:4]
IntraCol <- DarkCols[5]
AlphaCols <- DarkCols[6:7]

SimLegend <- c("Generic", "Intraspecific", "Species 6", "Species 14")

constdf <- data.frame(env.seq, t(GenericPlot), t(IntraPlot), t(SpecificPlot[1,,]), t(SpecificPlot[2,,])) %>%
        rename(gen.mean = X1, gen.low = X2, gen.high = X3,
               intra.mean = X1.1, intra.low = X2.1, intra.high = X3.1,
               sp1.mean = X1.2, sp1.low = X2.2, sp1.high = X3.2,
               sp2.mean = X1.3, sp2.low = X2.3, sp2.high = X3.3) %>%
        pivot_longer(!env.seq, names_to = "sp", values_to = "alpha") %>%
        separate(sp, into = c("species", "value")) %>%
        pivot_wider(names_from = "value", values_from = "alpha")

p.const.nointra <- ggplot(filter(constdf, species != "intra"), aes(x = env.seq, y = mean)) +
        ylim(c(0, 0.02)) +
        geom_ribbon(alpha = 0.3, aes(ymin = low, ymax = high, fill = species)) +
        geom_line(aes(color = species)) +
        ylab(AlphaLab) +
        theme_cw() +
        xlab("Environment") + 
        scale_color_manual(values = c('black', AlphaCols),
                           labels = c("Generic", "Species 6", "Species 14"),
                           name = "") +
        scale_fill_manual(values = c('black', AlphaCols),
                          labels = c("Generic", "Species 6", "Species 14"),
                          name = "") +
        theme(axis.title.y = element_text(size = 16), 
              legend.position = c(0.2,0.85), 
              legend.background = element_rect(fill = "white", color = "white")) 


p.const.intra <- ggplot(filter(constdf, species == "intra"), aes(x = env.seq, y = mean)) +
        ylim(c(0, 0.08)) +
        geom_ribbon(alpha = 0.3, aes(ymin = low, ymax = high, fill = species)) +
        geom_line(aes(color = species)) +
        ylab(AlphaLab) +
        theme_cw() +
        xlab("Environment") + 
        scale_color_manual(values = IntraCol,
                           labels = "Intraspecific",
                           name = "") +
        scale_fill_manual(values = IntraCol,
                          labels = "Intraspecific",
                          name = "") +
        theme(axis.title.y = element_text(size = 16), 
              legend.position = c(0.6,0.2)) 

p.const.both <- p.const.nointra + 
        inset_element(p.const.intra, left = 0.35, bottom = 0.5, right = 1, top = 1)


p.const <- ggplot(constdf, aes(x = env.seq, y = mean)) +
        geom_ribbon(alpha = 0.3, aes(ymin = low, ymax = high, fill = species)) +
        geom_line(aes(color = species)) +
        theme_cw() +
        ylab(AlphaLab) +
        xlab("Environment") + 
        scale_color_manual(values = c('black', IntraCol, AlphaCols),
                           labels = c("Generic", "Intraspecific", "Species 6", "Species 14"),
                                      name = "") +
        scale_fill_manual(values = c('black', IntraCol, AlphaCols),
                          labels = c("Generic", "Intraspecific", "Species 6", "Species 14"),
                                     name = "") +
        theme(axis.title.y = element_text(size = 16), 
              legend.position = c(0.8,0.85), 
              legend.background = element_rect(fill = "white", color = "white")) 
        

### Box figure combining parts ---------------

#patchwork <- (p.mono + p.opt) / (a.post + a.terms)
patchwork <- (p.mono / p.opt) | p.const

patchwork + 
        plot_annotation(tag_levels = 'a')  & 
        theme(plot.tag = element_text(face = "bold"))

# ggsave(filename = here('BH_simulations/Box/box_figure_R1b.pdf'), width = 10, height = 6, units = 'in')


# Other option with inset figure for intraspecific

patchwork <- (p.mono / p.opt) | p.const.both

patchwork + 
        plot_annotation(tag_levels = 'a')  & 
        theme(plot.tag = element_text(face = "bold"))

# ggsave(filename = here('BH_simulations/Box/box_figure_R1c.pdf'), width = 10, height = 6, units = 'in')


